language: ruby
cache: bundler

sudo: required

services: docker

env:
  - PHP_VERSION=56
  - PHP_VERSION=70

script: echo $DOCKER_PASSWORD; echo $DOCKER_USERNAME


after_success:
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" dockerrepo.stack.provider.nl:5000;
    docker push dockerrepo.stack.provider.nl/test-php-$PHP_VERSION;
